env:
  AWS_ACCOUNT_ID: "253213882263"
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/buildkite-ecs-oidc-example"
  CONTAINER_TAG: "${ECR_REPOSITORY}:${BUILDKITE_BUILD_NUMBER}"

steps:
  - label: ":docker:"
    command: |
      docker build -t "${CONTAINER_TAG}" --platform=linux/amd64 .
      docker push "${CONTAINER_TAG}"
    plugins:
      - ecr#v2.7.0:
          login: true
          account_ids: "${AWS_ACCOUNT_ID}"
          region: "${AWS_REGION}"

  - wait

  - label: ":ecs: :rocket:"
    branches: main
    agents: queue=deploy
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::253213882263:role/deploy-ecs

      - ecs-deploy:
          region: us-east-1
          cluster: "buildkite-ecs-oidc-example"
          service: "buildkite-ecs-oidc-example"
          task-family: "buildkite-ecs-oidc-example"
          container-definitions: "container-definitions.json"
          task-definition: "task-definition.json"
          image: "${CONTAINER_TAG}"
